### ISSUE TITLE
Best practice for adding instances to "derived" Records

### ISSUE THREAD

**Issue by bbarker** [danidiaz/red-black-record#17]
Perhaps this could be a good example for the docs. I assume it is just to use newstyping, 

But let's say `addFieldI` is used to create a new record from a haskell data type record; is there a way to more or less automatically "inherit" the instances of the original Haskell data type record?

Currently my plan would be to create a `newtype` wrapper for the base Record type after using `toRecord`, then use DerivingVia; but I've not thought of a way to have this automatically extend to other record types that have been wrapped, but have extended the base record with `addFieldI`.

**Comment by danidiaz** [comment]
There's no automatic way to inherit instances from the original record, I'm afraid. `DerivingVia` isn't likely to help because a newtype-wrapped `Record` and the original record don't really share the same representation.

Right now `Record`s don't have typeclass instances other than `Show`. Perhaps I should add some other basic instances like `Eq`, `Ord`,`Monoid`... they would be implemented in terms of the existing instances of the [`NP`](http://hackage.haskell.org/package/sop-core-0.5.0.0/docs/Data-SOP.html#t:NP) type from sop-core.

**Comment by bbarker** [comment]
A related notion that *might* help in some cases is using [GHC.Records' HasField](https://stackoverflow.com/a/42790994/3096687), though I see you have some notes on this already.

On my end, what I'm fairly sure I need is a slight extension of the functionality of [applyRecFun](https://stackoverflow.com/a/58938566/3096687), where I instead have

applyRecFun :: forall r1 r2 t. (Traversable t, Semigroup (t r1), Semigroup (t r2) _) =>
  Record (SummaryFun t) _ -> t r1 -> Maybe r2

So we get out a different record type (`r2`) than we got in (`r1`), but there are still some constraints that should be imposed on both `r1` and `r2` (e.g. that have instances of a particular class related to my application domain). This sounds tricky for me, and maybe it is.

Perhaps a better solution is to just have:

applyRecFun :: forall r e t. (Traversable t, Semigroup (t r), Semigroup (t e) _) =>
  Record (SummaryFun t) _ -> t r -> Maybe (r, e)

Where e ("e" stands for "extra") is an extra record with all the extra fields created.

But this implies `newtype SummaryFun t a = SummaryFun (t a -> a)` is too simple; after all, where are the extra fields coming from? Maybe `newtype SummaryFun t a = SummaryFun (t a -> (a,  e))` where each function possibly adds extra fields. But what if we want to do some statistics that works on multiple fields? In that case we could keep the original `SummaryFun` but provide an additional function `t r -> e` that operates on a list of entire records, to generate the extra record of type `e`.

Sorry for thinking out loud, I'll play around with this more in the afternoon.

**Comment by danidiaz** [comment]
I'm not sure I understand the "extra data" case. Could you give a more concrete example?

(Also—somewhat unrelatedly—the [foldl](http://hackage.haskell.org/package/foldl) package can be quite useful for structuring these kinds of "summary value" computations. The `Fold` type there has an `Applicative` instance that combines computations. Another nice thing is that the `Fold`s themselves are agnostic about the source of the data.)

**Comment by bbarker** [comment]
For extra data, I mean things like this: without the extra data, we could construct our summary record using values calculated by `sum`, `mean` (to asses aggregates), or `head` (to grab the first element of a list that would always be the same. But some of the original fields might calculate multiple values for the same original field: not just the `sum`, but maybe also the `mean`, `standard deviation`, etc.

I'll take a look at the `foldl` package. It seems that the `Traversable` and `Semigroup` requirements may be causing issues already with the below implementation:

```haskell
newtype SummaryFun t a = SummaryFun (t a -> a)

applyRecFun :: forall r t. (Traversable t, Semigroup (t r), _) =>
  Record (SummaryFun t) _ -> t r -> Maybe r
applyRecFun func recs =
  let recsNP :: t (NP I _) -- n-ary products. I is an identity functor
      recsNP = toNP . toRecord <$> recs
      listrecsNP :: t (NP t _) -- turn every field into a singleton
      listrecsNP = liftA_NP (\(I x) -> pure x) <$> recsNP
      listrecNPmay :: Maybe (NP t _) -- an n-ary product where each field is a t
      listrecNPmay = listrecsNP & (headMay &&& tailMay) & sequenceT
        <&> (\(h, t) -> foldr mappend h t)
      funcNP :: NP (SummaryFun t) _ -- turn the function record into a n-ary prod
      funcNP = toNP func
      toRec_NP_I :: NP t _ -> NP I _ -- apply the functions to each field
      toRec_NP_I = liftA2_NP (\(SummaryFun f) vs -> I (f vs)) funcNP
   in do
    listrecNP <- listrecNPmay
    let resultRec_NP_I = toRec_NP_I listrecNP
    pure $ fromRecord . fromNP $ resultRec_NP_I -- go back to the nominal record
```

For instance, using it like this:

```haskell
  let allRecs :: LNE.NonEmpty SxRecord = fromJust allRecsMay
  let summaryRec = applyRecFun defaultStatsSx allRecs
```

evokes a somewhat confusing error on the second `let`:

```
    • No instance for (Monoid (LNE.NonEmpty (Maybe Double)))
        arising from a use of ‘applyRecFun’
    • In the expression: applyRecFun defaultStatsSx allRecs
      In an equation for ‘summaryRec’:
          summaryRec = applyRecFun defaultStatsSx allRecs
```

I think this is due to `SemiGroup` working with `Maybe` to form a `Monoid`.
